version: '2'
services:
  app:
    build: .
    tty: true
    environment:
      RAILS_ENV: development
      DATABASE_URL: mysql2://root:devpass@mysql:3306
    ports:
      - '3000:3000'
    volumes:
      - .:/work/myspace:cached

    links:
      - mysql
    networks:
      - common_link
  mysql:
    image: mysql:5.6.23
    environment:
      MYSQL_ROOT_PASSWORD: devpass
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - common_link
volumes:
  mysql-data:
    driver: local

networks:
  common_link:
    external: true

